apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: voting
    db: postgres
spec:
  containers:
    - name: db
      image: postgres:10
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres