apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    app: voting
    tier: voting-result
spec:
  containers:
    - name: result-app
      image: kodekloud/examplevotingapp_result:v1