apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    app: voting
spec:
  type: NodePort
  selector:
    tier: voting-result
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002