apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    app: voting
spec:
  type: NodePort
  selector:
    tier: voting-entry
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001