apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: voting
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: voting-result
  template:
    metadata:
      name: result-app-pod
      labels:
        app: voting
        tier: voting-result
    spec:
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1