apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: voting
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: worker
  template:
    metadata:
      name: worker-pod
      labels:
        app: voting
        tier: worker
    spec:
      containers:
        - name: worker
          image: kodekloud/examplevotingapp_worker:v1